version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  product-service:
    build: ./backend/product-service
    depends_on:
      - postgres
    ports:
      - "8084:8080"
    volumes:
      - ./backend/product-service/:/var/www/productservice
  customer-service:
    build: ./backend/customer-service
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    volumes:
      - ./backend/customer-service/:/var/www/customerservice
  order-service:
    build: ./backend/order-service
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    volumes:
      - ./backend/order-service/:/var/www/orderservice
  frontend:
    build: ./frontend/ecommerce-ui
    ports:
      - "3000:80"
    depends_on:
      - product-service
      - customer-service
      - order-service
    volumes:
      - ./frontend/ecommerce-ui/:/var/www/html
volumes:
  postgres-data: