apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: ecommerce-app
    name: customer-service
spec:
  type: NodePort
  selector:
    app: ecommerce-app
    name: customer-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002