apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui-service
  labels:
    name: ecommerce-ui-service
    app: ecommerce-app
spec:
  type: NodePort
  selector:
    app: ecommerce-app
    name: ecommerce-ui-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004