apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  labels:
    name: order-deploy
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-pod
      app: ecommerce-app
  template:
    metadata:
      name: order-pod
      labels:
        name: order-pod
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-microservices-order-service
          image: ecommerce-microservices_order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
