apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-deploy
  labels:
    name: postgres-deploy
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: ecommerce-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: ecommerce-app
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "ecommerce"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
