apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    name: product-service
    app: ecommerce-app
spec:
  type: NodePort
  selector:
    app: ecommerce-app
    name: product-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001