apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels:
    name: product-deploy
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product-pod
      app: ecommerce-app
  template:
    metadata:
      name: product-pod
      labels:
        name: product-pod
        app: ecommerce-app
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:15
          command: [ 'sh', '-c', 'until pg_isready -h db -p 5432; do echo waiting for database; sleep 2; done;' ]
      containers:
        - name: ecommerce-microservices-product-service
          image: minhnt2012/ecommerce-microservices_product-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
